version: "3"

networks:
  ipfs:
    external:
      name: private-ipfs

services:
  bootstrap_node:
    #image: ipfs/go-ipfs:latest
    hostname: bootstrap_node
    networks:
      - ipfs
    build:
      context: private-network
      dockerfile: Dockerfile
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    expose:
      - 4001
      - 5001
    ports:
      - "4001:4001"
      - "5001:5001"
    volumes:
      - ./private-network/bootstrap_node/ipfs:/data/ipfs
      - ./private-network/init.sh:/usr/local/bin/start_ipfs

  ipfs_node:
    hostname: ipfs_node
    networks:
      - ipfs
    build:
      context: private-network
      dockerfile: Dockerfile
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    expose:
      - 4001
      - 5001
    ports:
      - "4001:4001"
      - "5001:5001"
    volumes:
      - ./private-network/ipfs_node/ipfs:/data/ipfs
      - ./private-network/init.sh:/usr/local/bin/start_ipfs

  dashboard:
    hostname: dashboard
    networks:
      - ipfs
    build:
      context: dashboard
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
