version: "3"

services:
  bootstrap_node:
    #image: ipfs/go-ipfs:latest
    hostname: bootstrap_node
    network_mode: host
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - ./private-network/bootstrap_node/ipfs:/data/ipfs
      - ./private-network/init.sh:/usr/local/bin/start_ipfs

  ipfs_node:
    hostname: ipfs_node
    network_mode: host
    build:
      context: private-network
    environment:
      LIBP2P_FORCE_PNET: "1"
      SWARM_PEER:
    volumes:
      - ./private-network/ipfs_node/ipfs:/data/ipfs
      - ./private-network/init.sh:/usr/local/bin/start_ipfs
